@host = localhost:5000

// Create User
POST http://{{host}}/api/users HTTP/1.1
content-type: application/json
    
{
    "username": "John Doe",
    "password": "password123",
    "biography": "I love UF so muuch, this place rules."
}

###

// Get User By ID
GET http://{{host}}/api/users/23 HTTP/1.1
content-type: application/json

###

// Get All User
GET http://{{host}}/api/users/ HTTP/1.1
content-type: application/json

###

// Update User
PUT http://{{host}}/api/users/3 HTTP/1.1
content-type: application/json

{
    "username": "MATT",
    "password": "acktumally",
    "biography": "Da!"
}

###

// Delete User
DELETE http://{{host}}/api/users/4 HTTP/1.1
content-type: application/json